### ISSUE TITLE
API Key exposed to clients

### ISSUE THREAD

**Issue by tbergmueller** [authenticvision/metaanchor#20]
With the current structure (as of commit ), the MetaAnchor-API key is exposed to the client. This is, because Communication with the API is done frontend-side and not within `getServersideProps()`

![image](https://github.com/authenticvision/metaanchor/assets/2257335/9f3f1b6c-366a-4ce3-9d35-e9cee97d27d3)

This violates the following requirement from #2 

> The MetaAnchor-API-Key (provided to users of the framework with the physical labels) as well as other secrets / keys must be well protected. Especially when people with mediocre programming and IT-Security skills edit the provided software in this repo, it shall be very hard to accidentially expose those keys

*Acceptance*
- From within a browser or any other client, it is impossible to retrieve or sniff any direct communication with MetaAnchor-API.

**Comment by pedrolucasp** [comment]
Good catch. I'll also file a ticket to do a sec. audit so we can catch mistakes like that before going live.
